name: Windows Build

on:
  push:
    branches: [ "main", "master", "movable-edges" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Устанавливаем Qt для компилятора MSVC 2019 (он совместим с Windows 2022)
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'  # ВАЖНО: Используем MSVC вместо MinGW
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        cache: 'true'

    # Настраиваем окружение для MSVC компилятора
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    # Сборка проекта
    - name: Build
      run: |
        qmake
        nmake
        
    # Упаковка (сборка в папку dist вместе с DLL)
    - name: Deploy (Package DLLs)
      run: |
        mkdir dist
        copy release\*.exe dist\
        windeployqt --release --compiler-runtime dist\*.exe

    # Загрузка результата на сайт
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GraphEditor-Windows
        path: dist/
